# Generated by Django 4.2.5 on 2023-09-09 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='township-image')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.district')),
            ],
        ),
    ]
