# Generated by Django 4.2.5 on 2023-09-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_district_created_district_updated_township_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='township',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
