# Generated by Django 4.2.5 on 2023-09-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_rename_village_home_villagehome_villagehome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villagehome',
            old_name='villagehome',
            new_name='village',
        ),
        migrations.RemoveField(
            model_name='villagehome',
            name='home_id',
        ),
        migrations.AddField(
            model_name='villagehome',
            name='homenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='villagehome',
            name='owner',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='TownshipWard',
        ),
    ]
