# Generated by Django 4.2.5 on 2023-09-18 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_rename_villagehome_villagehome_village_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homenumber', models.IntegerField()),
                ('owner', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ward')),
            ],
        ),
        migrations.DeleteModel(
            name='VillageHome',
        ),
    ]
