# Generated by Django 4.2.5 on 2023-09-18 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_wardhome_delete_villagehome'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homenumber', models.IntegerField()),
                ('owner', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.village')),
            ],
        ),
    ]
